name: PyPI

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Setup Python 3.11
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'

    - name: Setup Poetry
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        pip install --upgrade pip
        pip install pipx
        pipx install poetry
        poetry config pypi-token.pypi $PYPI_TOKEN

    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Install
      run: poetry install

    - name: Build
      run: poetry build

    - name: Publish
      run: poetry publish
